- debian/switchboard-plug-security-privacy.install
> Add missing directory in build files to ensure schema included

- src/Widgets/AppChooser.vala
- src/Widgets/AppRow.vala
Similar fix as: https://github.com/elementary/switchboard-plug-applications/pull/15#issuecomment-369063850
> Limit width AppChooser

- src/Views/LocationPanel.vala
> Add a placeholder to location services

- po/POTFILES
- src/Plug.vala
- src/Views/HouseKeepingPanel.vala
- src/Widgets/ServiceItem.vala
- src/Widgets/ServiceList.vala
- src/meson.build
> Create a Housekeeping panel

- src/Plug.vala
> Use new settings URLs

- src/Widgets/ExcludeTreeView.vala
> ExcludeTreeView: Use FileChooserNative

- src/Views/HouseKeepingPanel.vala
- src/Widgets/ServiceList.vala
> Use housekeeping icon

- src/Views/HouseKeepingPanel.vala
> HouseKeepingPanel: Redesign after Onboarding

- src/Views/FirewallPanel.vala
This fixes linting errors in the FirewallPanel file.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint src/Views/FirewallPanel.vala
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint src/Views/FirewallPanel.vala
```
> Firewall panel lint

- data/io.elementary.switchboard.security-privacy.appdata.xml.in
> AppData: Add release data

- src/Views/FirewallPanel.vala
> Switch from Toolbar to Actionbar

- src/Widgets/ExcludeTreeView.vala
Finish #96 
Somehow missed this in the first PR
> Switch to ActionBar

- data/io.elementary.switchboard.security-privacy.appdata.xml.in
For better display in Feedback and AppCenter
> AppData: Add "Settings" to name

- data/io.elementary.switchboard.security-privacy.appdata.xml.in
- meson.build
Last release for Bionic. After this lockscreen gsettings will change and packaging will need to be updated
> Release 2.2.4

- debian/control
Goes with https://github.com/elementary/switchboard-plug-security-privacy/pull/111
> Control: Update runtime depends

- src/Views/LockPanel.vala
In conjunction with:
https://github.com/elementary/gala/pull/820
> Use GNOME key to enable screen locking

- src/Widgets/AppChooser.vala
- src/Widgets/ExcludeTreeView.vala
* Initialize objects with properties
* Remove single-use method
* organize
* Use Gtk.MenuButton
> AppChooser: cleanup

- data/security-privacy.metainfo.xml.in
- meson.build
Changes us over to using location portal
> Release 7.0.0

- src/Plug.vala
- src/Views/FirewallPanel.vala
Move lock and permission object into this panel since it only affects this panel
> FirewallPanel: handle locking internally

- src/Views/HouseKeepingPanel.vala
Use settings from https://github.com/elementary/settings-daemon/pull/143
cleanup names while we're here
> Housekeeping: use elementary settings-daemon
